spring:
  application:
    name: Easy-AI-Agent

  profiles:
    active: local

langchain4j:
  community:
    dashscope: #千问模型配置
      chat-model:
        api-key:
        model-name:
      embedding-model: #文本统一向量模型
        api-key:
        model-name: